#!/usr/bin/env bash
# Redirect
apt-get -y update
apt-get -y install nginx
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

printf %s "server {
    listen		80 default_server;
    listen		[::]:80 default_server;
    root		/var/www/html;
    index		index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
	try_files \$uri \$uri/ =404;
	}
	rewrite ^/redirect_me https://www.youtube.com/watch?v=AMUs9KPMqj8&list=LL&index=85 permanent;
}\
" > /etc/nginx/sites-available/default

service nginx restart
