#!/usr/bin/env bash
# Run nginx as nginx
sudo pkill apache2
sudo sed -i "sed -i "s/$user/nginx;/g" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
